### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by PatriceVigier** [DavidIQ/captchaplus#1]
Hello,

PhpBB 3.2.5

I got the following error

Something went wrong during the request and an exception was thrown. The changes made before the error occurred were reversed to the best of our abilities, but you should check the board for errors.

The migration "\davidiq\captchaplus\migrations\install_permissions" is not fulfillable, missing migration "\phpbb\db\migration\data\v330\v330".

What can I do?

Thank you
Sincerely

**Comment by DavidIQ** [comment]
Upgrade forum to 3.3. This extension was not designed to support 3.2. The migration makes sure it is not installed in a lower version.

**Comment by PatriceVigier** [comment]
Thank you for your answer that I was guessing :=)
Your project is great and I do not understand why it is not standard on phpbb. I have red so many post asking for it.
When I have some time, because I know upgrading is never easy, I will and install your plugin.
Good luck
Patrice
